name: 执行上传任务

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  call_workflow:
    uses: misaka-org/Chaoxing-MiniProgram/.github/workflows/origin.yaml@main
    secrets:
      APPID: ${{ secrets.APPID }}
      KEY: ${{ secrets.KEY }}

